### ISSUE TITLE
Downloading renderer 99%

### ISSUE THREAD

**Issue by Enfostorm** [laurent-clouet/sheepit-client#130]
The first time I started the client, everything worked fine, but when I started another session, the status would just stay at starting. If I removed the files from /tmp (temp file in linux), the client would download the renderer again, but would get stuck at 99%, and it would not start extracting the file.

Here's the output from the terminal:
```
java -jar ./sheepit-client-5.495.2848.jar 
GPU::generate failed to load CUDA lib (path: cuda)
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.sheepit.client.Utils.md5(Utils.java:75)
	at com.sheepit.client.Client.checkFile(Client.java:687)
	at com.sheepit.client.Client.downloadFile(Client.java:649)
	at com.sheepit.client.Client.downloadExecutable(Client.java:633)
	at com.sheepit.client.Client.work(Client.java:574)
	at com.sheepit.client.Client.run(Client.java:315)
	at com.sheepit.client.standalone.GuiSwing$ThreadClient.run(GuiSwing.java:339)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 7 more
```

I'm running ubuntu 16.04

**Comment by laurent-clouet** [comment]
I'm guessing you are using java9.
https://www.sheepit-renderfarm.com/getstarted.php#java9

**Comment by Enfostorm** [comment]
I do indeed have java9 (which I did not realise before), but if I run the command (in linux the command seems to be `java --add-modules java.xml.bind -jar ./sheepit-client.jar` instead of `-addmods`, java -h does not list `-addmods`)
However, if I run the .jar file that way, it says there is no job available, and it will check again in 15 minutes. 
Also, it does not list any data relating to my account (credits, machines connected etc.).
Command line stays empty.
Java version:
```
java version "9"
Java(TM) SE Runtime Environment (build 9+175)
Java HotSpot(TM) 64-Bit Server VM (build 9+175, mixed mode)
```

**Comment by Enfostorm** [comment]
Here's the entire verbose output if you feel the need to take a look at it.
[sheepitfarm -verbose.txt](https://github.com/laurent-clouet/sheepit-client/files/1120715/sheepitfarm.-verbose.txt)

**Comment by Enfostorm** [comment]
I searched for sheepit in my root directory, deleted all the files I could find that had to do with Sheepit-client, redownloaded the .jar, ran it with the --add-modules option, and it seems to be working fine again. Is it possible that the client can not handle it if a directory already exists?
