### ISSUE TITLE
Client not starting..

### ISSUE THREAD

**Issue by michaelbukachi** [laurent-clouet/sheepit-client#131]
Hello. I'm getting the following error when trying to start the client. I'm running it on a virtual server.
`
21-07 06:47:11 (debug) client version 5.495.2848
Starting
21-07 06:47:11 (debug) GUI Starting
21-07 06:47:11 (debug) Client::run exception(D) java.lang.NullPointerException stacktrace: java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at com.sheepit.client.Server.getConfiguration(Server.java:186)
	at com.sheepit.client.Client.run(Client.java:128)
	at com.sheepit.client.standalone.GuiText.start(GuiText.java:82)
	at com.sheepit.client.standalone.Worker.doMain(Worker.java:316)
	at com.sheepit.client.standalone.Worker.main(Worker.java:107)
`

**Comment by laurent-clouet** [comment]
can you try this one: https://www.phyrexia.org/dl/50KYFNQ2
it will not fix the issue but it should tell me where is it exactly

**Comment by michaelbukachi** [comment]
Here's the output:

```21-07 15:53:41 (debug) client version 5.0.0
Starting
21-07 15:53:41 (debug) GUI Starting
DEBUG config Configuration (workingDirectory '/tmp/farm_2377751176289558719')
DEBUG OS Linux [NICE_BINARY_PATH=nice, hasNiceBinary=null]
DEBUG CPU CPU [name=Intel Xeon E312xx (Sandy Bridge), model=42, family=6, arch=64bit]
21-07 15:53:41 (debug) Client::run exception(D) java.lang.NullPointerException stacktrace: java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at com.sheepit.client.Server.getConfiguration(Server.java:204)
	at com.sheepit.client.Client.run(Client.java:128)
	at com.sheepit.client.standalone.GuiText.start(GuiText.java:82)
	at com.sheepit.client.standalone.Worker.doMain(Worker.java:316)
	at com.sheepit.client.standalone.Worker.main(Worker.java:107)

21-07 15:53:41 (debug) Server::HTTPRequest url()```

**Comment by laurent-clouet** [comment]
Can you try this one: https://www.sheepit-renderfarm.com/media/applet/sheepit-client-5.497.2853.jar

**Comment by michaelbukachi** [comment]
It works now :) What was the issue?

**Comment by laurent-clouet** [comment]
The detection of hostname is failing. I'm guessing you didn't fill up the /etc/hosts for localhost/127.0.0.1

**Comment by laurent-clouet** [comment]
1683eb02c5a088a9768c57efb7eb3f2cee765ee fix the issue.
