### ISSUE TITLE
GUI Client gives NETWORK_ISSUE and will not start rendering

### ISSUE THREAD

**Issue by jBot-42** [laurent-clouet/sheepit-client#26]
This is with version 3.166.2217 of the client on Mac OS 10.10. When run in the command line it returns this and quits:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/sheepit/client/standalone/Worker : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by laurent-clouet** [comment]
Hello,

Give message means that you don't have the right version of java. 
It's a message you get when you are trying to run on java 1.6 BUT you need Java 1.7.

**Comment by jBot-42** [comment]
I have Java version 1.7.0_79 which the Java website says is the latest version. Also, when I run the web client, it does not start and displays this in the Java console:

```
FarmClient init
FarmClient init continue
FarmClient start
FarmClient run
exception java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.sheepit.client.os.Mac.getCPU(Mac.java:59)
	at com.sheepit.client.Configuration.checkCPUisSupported(Configuration.java:330)
	at com.sheepit.client.Client.run(Client.java:100)
	at com.sheepit.client.applet.Worker.run(Worker.java:134)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=1, Operation not permitted
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
exception java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.sheepit.client.os.Mac.getCPU(Mac.java:59)
	at com.sheepit.client.Server.getConfiguration(Server.java:172)
	at com.sheepit.client.Client.run(Client.java:113)
	at com.sheepit.client.applet.Worker.run(Worker.java:134)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=1, Operation not permitted
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
exception java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.sheepit.client.os.Mac.getCPU(Mac.java:59)
	at com.sheepit.client.Server.getConfiguration(Server.java:172)
	at com.sheepit.client.Client.run(Client.java:113)
	at com.sheepit.client.applet.Worker.run(Worker.java:134)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=1, Operation not permitted
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
exception java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.sheepit.client.os.Mac.getCPU(Mac.java:59)
	at com.sheepit.client.Server.getConfiguration(Server.java:172)
	at com.sheepit.client.Client.run(Client.java:113)
	at com.sheepit.client.applet.Worker.run(Worker.java:134)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=1, Operation not permitted
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
exception java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.sheepit.client.os.Mac.getCPU(Mac.java:59)
	at com.sheepit.client.Server.getConfiguration(Server.java:172)
	at com.sheepit.client.Client.run(Client.java:113)
	at com.sheepit.client.applet.Worker.run(Worker.java:134)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=1, Operation not permitted
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
exception java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.sheepit.client.os.Mac.getMemory(Mac.java:108)
	at com.sheepit.client.Server.getConfiguration(Server.java:172)
	at com.sheepit.client.Client.run(Client.java:113)
	at com.sheepit.client.applet.Worker.run(Worker.java:134)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=1, Operation not permitted
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
exception java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
java.io.IOException: Cannot run program "sysctl": error=1, Operation not permitted
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.sheepit.client.os.Mac.getCPU(Mac.java:59)
	at com.sheepit.client.Server.getConfiguration(Server.java:172)
	at com.sheepit.client.Client.run(Client.java:113)
	at com.sheepit.client.applet.Worker.run(Worker.java:134)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=1, Operation not permitted
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
07-07 11:15:44 (error) Server::getConfiguration error UnknownHostException java.net.UnknownHostException: jmbp.local: jmbp.local: nodename nor servname provided, or not known
FarmClient exited
FarmClient stop
```

**Comment by laurent-clouet** [comment]
Ok that's a different issue.
I'll get my hand on a mac osx 10.10 to check what is going on.

Thanks for the report!

**Comment by laurent-clouet** [comment]
I'm not sure you have the same java between the Web browser and the command line.
Because the command line give you a "java 6 message" but the web browser can launch the applet.

Can you do a "java -version" on the command line to be sure.

**Comment by jBot-42** [comment]
Here is what java -version returns:
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

**Comment by jBot-42** [comment]
I have updated it and it now works. Thanks for the help!
