### ISSUE TITLE
Google Collab instances "disconnect" after a while

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [laurent-clouet/sheepit-client#275]
Working as normal up until I get this:

![image](https://user-images.githubusercontent.com/47691365/85890145-b5dff000-b7e4-11ea-8519-e5f71d232907.png)

**Comment by the-furry-hubofeverything** [comment]
From what I heard, the bug is going to be addressed in the next update

**Comment by ChickenSupreme** [comment]
I'm getting this as well on client version 6.2018.0:

```
Jul 06 02:50:44 Rendering project "DungeonTest4 0-570"
06-07 02:50:44 (debug) GUI Reusing cached renderer
Jul 06 02:50:44 Reusing cached renderer
Jul 06 02:50:44 Downloading project   0% [>                    ]            06-07 02:50:44 (debug) Server::HTTPRequest url(https://client.sheepit-renderfarm.com/server/archive.php?type=job&job=2861617)
06-07 02:52:31 (error) Server::HTTPGetFile Exception java.io.IOException: Unexpected response from HTTP Stacktimeout stacktrace java.io.IOException: Unexpected response from HTTP Stacktimeout
        at com.sheepit.client.Server.HTTPRequest(Server.java:416)
        at com.sheepit.client.Server.HTTPRequest(Server.java:385)
        at com.sheepit.client.Server.HTTPGetFile(Server.java:425)
        at com.sheepit.client.Client.downloadFile(Client.java:741)
        at com.sheepit.client.Client.downloadSceneFile(Client.java:720)
        at com.sheepit.client.Client.work(Client.java:654)
        at com.sheepit.client.Client.run(Client.java:327)
        at com.sheepit.client.standalone.GuiText.start(GuiText.java:87)
        at com.sheepit.client.standalone.Worker.doMain(Worker.java:332)
        at com.sheepit.client.standalone.Worker.main(Worker.java:98)

06-07 02:52:31 (debug) Client::run exception(D) java.lang.NullPointerException stacktrace: java.lang.NullPointerException
        at com.sheepit.client.Server.HTTPGetFile(Server.java:478)
        at com.sheepit.client.Client.downloadFile(Client.java:741)
        at com.sheepit.client.Client.downloadSceneFile(Client.java:720)
        at com.sheepit.client.Client.work(Client.java:654)
        at com.sheepit.client.Client.run(Client.java:327)
        at com.sheepit.client.standalone.GuiText.start(GuiText.java:87)
        at com.sheepit.client.standalone.Worker.doMain(Worker.java:332)
        at com.sheepit.client.standalone.Worker.main(Worker.java:98)

06-07 02:52:31 (debug) GUI Stopping
Jul 06 02:52:31 Stopping
06-07 02:52:36 (debug) GUI Disconnecting from SheepIt server
Jul 06 02:52:36 Disconnecting from SheepIt server
06-07 02:52:36 (debug) Server::HTTPRequest url(https://client.sheepit-renderfarm.com/account.php?mode=logout&worker=1)
```

**Comment by Raimund58** [comment]
Should be fixed with #274

**Comment by ChickenSupreme** [comment]
> Should be fixed with #274

I just cloned the source and compiled it myself and yes it does seem to be fixed. Thank you.

For what it's worth it still frequently fails to complete the HTTP request but at least it now retries instead of exiting completely. From my limited testing it seems like the server is often returning a 404 when requesting archive.php which is what's causing it.

**Comment by Raimund58** [comment]
@ThePortuguesePlayer The fix is now implemented in the newest client. So you might was to close this issue :)

**Comment by ThePortuguesePlayer** [comment]
Cool! Thanks.
