### ISSUE TITLE
When in container, client becomes stuck in a "Check computer strength." loop

### ISSUE THREAD

**Issue by Xalaxis** [laurent-clouet/sheepit-client#278]
When running the latest version of the client, 6.2018.0, in a Docker container, the client becomes stuck in a "Check computer strength." loop where it is never issued actual work.

The Docker container in use is https://github.com/fkrauthan/sheepit-docker

Perhaps this is a work upload bug, because the log seems to show upload issues?

```09-07 17:42:12 (debug) Saved: '/tmp/farm_8804670742333321283/6_0340.png'
09-07 17:42:12 (debug)  Time: 02:13.11 (Saving: 00:04.78)
09-07 17:42:12 (debug) Blender quit
09-07 17:42:12 (debug) end of rendering
09-07 17:42:12 (debug) Job::render pictureFilename: /tmp/farm_8804670742333321283/6_0340.png, size: 942063'
09-07 17:42:12 (debug) GUI Frame rendered in 2min13s
Jul 09 17:42:12 Frame rendered in 2min13s
Jul 09 17:42:12 Rendering
Jul 09 17:42:12 Compute method:
09-07 17:42:12 (debug) GUI Uploading frame (0.90MB)
Jul 09 17:42:12 Uploading frame (0.90MB)
09-07 17:42:12 (debug) Client::confirmeJob url https://client.sheepit-renderfarm.com/server/send_frame.php?job=6&frame=0340&extras=&rendertime=133&memoryused=98610
09-07 17:42:12 (debug) path frame /tmp/farm_8804670742333321283/6_0340.png
09-07 17:42:12 (debug) Server::HTTPSendFile(https://client.sheepit-renderfarm.com/server/send_frame.php?job=6&frame=0340&extras=&rendertime=133&memoryused=98610,/tmp/farm_8804670742333321283/6_0340.png)
09-07 17:42:12 (error) Server::HTTPSendFile, Exception java.lang.IllegalArgumentException: Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter $this$toMediaTypeOrNull stacktrace java.lang.IllegalArgumentException: Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter $this$toMediaTypeOrNull
        at okhttp3.MediaType$Companion.parse(MediaType.kt)
        at okhttp3.MediaType.parse(MediaType.kt)
        at com.sheepit.client.Server.HTTPSendFile(Server.java:497)
        at com.sheepit.client.Client.confirmJob(Client.java:875)
        at com.sheepit.client.Client.run(Client.java:358)
        at com.sheepit.client.standalone.GuiText.start(GuiText.java:87)
        at com.sheepit.client.standalone.Worker.doMain(Worker.java:332)
        at com.sheepit.client.standalone.Worker.main(Worker.java:98)

09-07 17:42:12 (debug) Sleep for 32s before trying to re-upload the frame
09-07 17:42:44 (debug) Server::HTTPSendFile(https://client.sheepit-renderfarm.com/server/send_frame.php?job=6&frame=0340&extras=&rendertime=133&memoryused=98610,/tmp/farm_8804670742333321283/6_0340.png)
09-07 17:42:44 (error) Server::HTTPSendFile, Exception java.lang.IllegalArgumentException: Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter $this$toMediaTypeOrNull stacktrace java.lang.IllegalArgumentException: Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter $this$toMediaTypeOrNull
        at okhttp3.MediaType$Companion.parse(MediaType.kt)
        at okhttp3.MediaType.parse(MediaType.kt)
        at com.sheepit.client.Server.HTTPSendFile(Server.java:497)
        at com.sheepit.client.Client.confirmJob(Client.java:875)
        at com.sheepit.client.Client.run(Client.java:358)
        at com.sheepit.client.standalone.GuiText.start(GuiText.java:87)
        at com.sheepit.client.standalone.Worker.doMain(Worker.java:332)
        at com.sheepit.client.standalone.Worker.main(Worker.java:98)

Jul 09 17:42:44 Frames rendered: 2
09-07 17:42:44 (debug) GUI Requesting Job
Jul 09 17:42:44 Requesting Job
09-07 17:42:44 (debug) Server::requestJob
09-07 17:42:44 (debug) Server::HTTPRequest url(https://client.sheepit-renderfarm.com/server/request_job.php?computemethod=1&cpu_cores=24&ram_max=25165824&rendertime_max=-1)
09-07 17:42:45 (debug) Server::handleFileMD5DeleteDocument delete old file /tmp/farm_8804670742333321283/db26b54689516484633b7d4855fb1567
Jul 09 17:42:45 Frames remaining: 0
Jul 09 17:42:45 Credits earned: 0
09-07 17:42:45 (debug) Got work to do id: 6 frame: 0340
Jul 09 17:42:45 Rendering project "Check computer strength."```

**Comment by MCOfficer** [comment]
Fixed in #227

**Comment by Xalaxis** [comment]
> Fixed in #277

I don't think that pull request is related, isn't that about non-fatal errors at the beginning of the render process?

**Comment by MCOfficer** [comment]
Sorry, I initially linked the wrong one. #277

**Comment by Xalaxis** [comment]
Thanks, I'll try compiling the latest version to see if that fixes things.

**Comment by Xalaxis** [comment]
I can confirm that fixes the issue, thanks for the help @MCOfficer 😃
