### ISSUE TITLE
Error in upload process: Expected a SETTINGS frame but was 7

### ISSUE THREAD

**Issue by ChucklesTheBeard** [laurent-clouet/sheepit-client#285]
```
31-07 14:43:59 (debug) Saved: '/tmp/sheep1/sheepit/2969348_3344.png'
31-07 14:43:59 (debug)  Time: 07:05.11 (Saving: 00:00.86)
31-07 14:43:59 (debug) Blender quit
31-07 14:44:00 (debug) end of rendering
31-07 14:44:00 (debug) Job::render pictureFilename: /tmp/sheep1/sheepit/2969348_3344.png, size: 3699963'
31-07 14:44:00 (debug) will validate Job (numFrame '3344' sceneMD5 '26e6195bba93ed071c468cdf0d0143b4' rendererMD5 '9df02fcf02fa02988e670c4c9ce2285d' ID '2969348' pictureFilename '/tmp/sheep1/sheepit/2969348_3344.png' jobPath 'szene_6.blend' gpu false name 'szene_6' extras '' updateRenderingStatusMethod 'remainingtime' render RenderProcess(startTime=1596220614204, endTime=1596221040067, remainingDuration=0, memoryUsed=1689350, coresUsed=6, process=null))
31-07 14:44:00 (debug) Client::confirmeJob url https://shepherd-gra-fr.sheepit-renderfarm.com/renderer/tile?token=15f2464c4901c6&id=14788217&rendertime=425&memoryused=1689350
31-07 14:44:00 (debug) path frame /tmp/sheep1/sheepit/2969348_3344.png
31-07 14:44:00 (debug) Server::HTTPSendFile(https://shepherd-gra-fr.sheepit-renderfarm.com/renderer/tile?token=15f2464c4901c6&id=14788217&rendertime=425&memoryused=1689350,/tmp/sheep1/sheepit/2969348_3344.png)
31-07 14:44:00 (debug) Server::requestJob
31-07 14:44:00 (error) Server::HTTPSendFile Error in upload process. Exception Expected a SETTINGS frame but was 7 stacktrace java.io.IOException: Expected a SETTINGS frame but was 7
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:110)
	at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:72)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
31-07 15:07:00 (debug) Saved: '/tmp/sheep1/sheepit/2969348_2273.png'
31-07 15:07:00 (debug)  Time: 09:46.17 (Saving: 00:00.60)
31-07 15:07:00 (debug) Blender quit
31-07 15:07:00 (debug) end of rendering
31-07 15:07:00 (debug) Job::render pictureFilename: /tmp/sheep1/sheepit/2969348_2273.png, size: 4065228'
31-07 15:07:00 (debug) will validate Job (numFrame '2273' sceneMD5 '26e6195bba93ed071c468cdf0d0143b4' rendererMD5 '9df02fcf02fa02988e670c4c9ce2285d' ID '2969348' pictureFilename '/tmp/sheep1/sheepit/2969348_2273.png' jobPath 'szene_6.blend' gpu false name 'szene_6' extras '' updateRenderingStatusMethod 'remainingtime' render RenderProcess(startTime=1596221833383, endTime=1596222420306, remainingDuration=0, memoryUsed=1689340, coresUsed=6, process=null))
31-07 15:07:00 (debug) Client::confirmeJob url https://shepherd-gra-fr.sheepit-renderfarm.com/renderer/tile?token=15f246987b7249&id=14787146&rendertime=586&memoryused=1689340
31-07 15:07:00 (debug) path frame /tmp/sheep1/sheepit/2969348_2273.png
31-07 15:07:00 (debug) Server::HTTPSendFile(https://shepherd-gra-fr.sheepit-renderfarm.com/renderer/tile?token=15f246987b7249&id=14787146&rendertime=586&memoryused=1689340,/tmp/sheep1/sheepit/2969348_2273.png)
31-07 15:07:00 (debug) Server::requestJob
31-07 15:07:01 (error) Server::HTTPSendFile Error in upload process. Exception Expected a SETTINGS frame but was 7 stacktrace java.io.IOException: Expected a SETTINGS frame but was 7
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:110)
	at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:72)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

running a build from https://github.com/laurent-clouet/sheepit-client/commit/3244bebbfad792be98004d81c9f0a98c6d0ecfd6

using: `sheepit-client --verbose -compute-method CPU -cores 6 -extras scheduler:slow_connectivity -login ChucklesTheBeard -password <snip> -memory 12G -theme dark -title "Sheep 1" -cache-dir /tmp/sheep1/`

This seems to happen intermittently. I've been seeing it for a while but thought it was related to the patch I was working on, and couldn't previously get a stack trace due to not having #283

**Comment by Raimund58** [comment]
This was not on Google Colab, right?

**Comment by ChucklesTheBeard** [comment]
Correct, my own hardware.

**Comment by MCOfficer** [comment]
This seems to be related to OkHttp: https://github.com/square/okhttp/issues/6082

**Comment by ChucklesTheBeard** [comment]
More, different logs from the same build:

```
05-08 09:35:34 (debug) Saved: '/tmp/sheep1/sheepit/2991496_0174.png'
05-08 09:35:34 (debug)  Time: 01:31:03.95 (Saving: 00:08.68)
05-08 09:35:34 (debug) Blender quit
05-08 09:35:39 (debug) end of rendering
05-08 09:35:39 (debug) Job::render pictureFilename: /tmp/sheep1/sheepit/2991496_0174.png, size: 10353129'
05-08 09:35:39 (debug) will validate Job (numFrame '0174' sceneMD5 '099d181acc4810780e06af127466246d' rendererMD5 '20eb01cbdc8d21c85ef744816caa83ea' ID '2991496' pictureFilename '/tmp/sheep1/sheepit/2991496_0174.png' jobPath 'sence2.blend' gpu true name 'sence2' extras '' updateRenderingStatusMethod 'remainingtime' render RenderProcess(startTime=1596629069893, endTime=1596634539344, remainingDuration=0, memoryUsed=934910, coresUsed=6, process=null))
05-08 09:35:39 (debug) Client::confirmeJob url https://shepherd-gra-fr.sheepit-renderfarm.com/renderer/tile?token=15f2a9fcea00e9&id=15531565&rendertime=5469&memoryused=934910
05-08 09:35:39 (debug) path frame /tmp/sheep1/sheepit/2991496_0174.png
05-08 09:35:39 (debug) Server::HTTPSendFile(https://shepherd-gra-fr.sheepit-renderfarm.com/renderer/tile?token=15f2a9fcea00e9&id=15531565&rendertime=5469&memoryused=934910,/tmp/sheep1/sheepit/2991496_0174.png)
05-08 09:35:39 (debug) Server::requestJob
05-08 09:35:40 (error) Server::HTTPSendFile Error in upload process. Exception exhausted all routes stacktrace java.io.IOException: exhausted all routes
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:135)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at com.sheepit.client.Server.HTTPSendFile(Server.java:510)
	at com.sheepit.client.Client.confirmJob(Client.java:937)
	at com.sheepit.client.Client.senderLoop(Client.java:554)
	at com.sheepit.client.Client$2.run(Client.java:161)
	at java.lang.Thread.run(Thread.java:748)

05-08 09:35:40 (debug) Sleep for 32s before trying to re-upload the frame
```
<next frame rendering stuff snipped>
```
05-08 09:36:12 (debug) Server::HTTPSendFile(https://shepherd-gra-fr.sheepit-renderfarm.com/renderer/tile?token=15f2a9fcea00e9&id=15531565&rendertime=5469&memoryused=934910,/tmp/sheep1/sheepit/2991496_0174.png)
05-08 09:36:12 (error) Server::HTTPSendFile Error in upload process. Exception Expected a SETTINGS frame but was 7 stacktrace java.io.IOException: Expected a SETTINGS frame but was 7
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:110)
	at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:72)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The frame shows up on https://www.sheepit-renderfarm.com/index.php?show=frames as of 09:42, https://www.sheepit-renderfarm.com/session.php?id=508348 doesn't show it validated, the GUI shows 0 frames queued for upload, and there are no further log entries referencing this frame.

**Comment by luguina** [comment]
I'll take a look at this one!

**Comment by luguina** [comment]
Hi @ChucklesTheBeard, I haven't been able to reproduce the errors :disappointed: Since yesterday I've rendered and sent close to 3,000 frames with no similar errors (some scattered download and job assignation errors though). This is the configuration in my 5 machines:

_uname -o -r_
5.3.0-64-generic GNU/Linux

_java -version_
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu219.10)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu219.10, mixed mode, sharing)

My guess is the error is related with the Java version but will configure a couple of VMs with your exact configuration to try replicating the issue.

**Comment by ChucklesTheBeard** [comment]
I've made a workaround; just block the one shepherd that causes network problems for me.

https://github.com/ChucklesTheBeard/sheepit-client/commit/bccc38a8bdf586c3d55068cdec5b55d31766d6c0
