### ISSUE TITLE
The client silently crashes on Windows 10 (but works if I run it without GUI)

### ISSUE THREAD

**Issue by Lissanro** [laurent-clouet/sheepit-client#291]
The client (sheepit-6.2020.0.exe) crashes on startup without any error messages. To debug the issue, I decided to unpack it and run manually:
```
PS C:\Users\Lissanro\Downloads\sheepit-6.2020.0> .\bin\java.exe -jar .\sheepit-client.jar
OpenCL::getInfodeviceString failed(H) status: -30 type: 16440
Exception in thread "main" java.lang.NullPointerException
        at com.sheepit.client.standalone.swing.activity.Settings.show(Settings.java:322)
        at com.sheepit.client.standalone.GuiSwing.showActivity(GuiSwing.java:299)
        at com.sheepit.client.standalone.GuiSwing.start(GuiSwing.java:151)
        at com.sheepit.client.standalone.Worker.doMain(Worker.java:332)
        at com.sheepit.client.standalone.Worker.main(Worker.java:98)
```
I have tried installing latest NVidia driver and the issue did not change. At first I thought the crash happens because of OpenCL error, but running --show-gpu does not cause the crash even though triggers the same OpenCL error:
```
.\bin\java.exe -jar .\sheepit-client.jar --show-gpu
OpenCL::getInfodeviceString failed(H) status: -30 type: 16440
GPU_ID    : CUDA_0
Long ID   : CUDA_GeForce GTX 680_0000:01:00
Model     : GeForce GTX 680
Memory, MB: 4096
```
I decided to try --ui text and I was able to render projects on GPU without issues. So it is something in swing (the GUI) that causes the crash.

**Comment by laurent-clouet** [comment]
I looks like gpu is enabled but it failed to get the gpudevice which is strange since you can list it.
Can you show the content of the config file (simply remove the password/public-key)
It's in your home directory, file ".sheepit.conf".

**Comment by Lissanro** [comment]
Sure. I think I found what triggers the bug, so I'm going to show only relevant lines:
```
compute-method=CPU_GPU
compute-gpu=CUDA_GeForce GTX 650_0000\:01\:00
```
The video card on this PC was upgraded since .sheepit.conf was created, so it fails to find the old card. Removing compute-gpu line did not work, I had to manually replace Long ID with new one and add backslashes before colons to make the GUI work again.

I'm still getting OpenCL error and a different NullPointerException: https://pastebin.com/vTdg6pJK (in AWT-EventQueue-0 thread this time) - but despite these errors, GUI works after applying the workaround mentioned above. So I'm assuming remaining errors are not related to this issue.

This seems to be a bug: if compute-gpu is invalid, instead of crashing silently, just reset to CPU-only rendering and then the user can enable new GPU manually (or, alternatively, replace compute-gpu value with first valid GPU Long ID and if there is none, use CPU-only).

This suggests a way to reproduce the bug - just change compute-gpu to something that does not exist. From user point of view, it is not obvious at all how to fix this issue since there are no visible errors after running the .exe file, and even after manually unpacking the client and running it from command line it did not report any easy to understand errors either. In other words, the client seems to assume that users will never upgrade their videocard.
