### ISSUE TITLE
Crash when the system doesn't support systray

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#38]
On the latest "Elementary OS" the client crash with this log:

user@elemtary:/media/sf_SheepitClient$ java -jar bin/sheepit-client.jar --verbose
07-09 15:44:40 (debug) client version 3.3.2
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.sheepit.client.standalone.Worker.doMain(Worker.java:282)
	at com.sheepit.client.standalone.Worker.main(Worker.java:92)
Caused by: java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.awt.SystemTray.getSystemTray(SystemTray.java:186)
	at com.sheepit.client.standalone.GuiSwing.<clinit>(GuiSwing.java:55)
	... 2 more
user@elemtary:/media/sf_SheepitClient$

**Comment by Creator13** [comment]
I think I found the problem. When the GuiSwing class is initialized (Worker.java:282), it automatically invokes a static SystemTray.getSystemTray(). I'm working on fixing the issue, but first I need to resync the GitHub stuff..

**Comment by laurent-clouet** [comment]
Yes it was that.
I was working on UI so I fixed it right away.

**Comment by Creator13** [comment]
Ah, great!

**Comment by laurent-clouet** [comment]
I was a bug report from a user this morning.
I actually created the bug to have an trace somewhere but i got the patch before i created the bug report.

Fixed by 2528392068b2fc0d36f0e21e0c83a29b84e613d7
