### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by laurent-clouet** [laurent-clouet/sheepit-client#43]
On svn version 171 (2015-07-20 17:45:38 +0100)

12-10 18:37:37 (debug) Server::requestJob
12-10 18:37:37 (debug) Client::run exception com.sheepit.client.exception.FermeException: error requestJob: unknow exception java.lang.NullPointerException stacktrace: java.lang.NullPointerException
   at java.util.Objects.requireNonNull(Objects.java:203)
   at java.util.Arrays$ArrayList.(Arrays.java:3813)
   at java.util.Arrays.asList(Arrays.java:3800)
   at com.sheepit.client.Configuration.getLocalCacheFiles(Configuration.java:274)
   at com.sheepit.client.Server.generateXMLForMD5cache(Server.java:815)
   at com.sheepit.client.Server.requestJob(Server.java:294)
   at com.sheepit.client.Client.run(Client.java:160)
   at com.sheepit.client.standalone.GuiSwing$ThreadClient.run(GuiSwing.java:191)
stacktrace: com.sheepit.client.exception.FermeException: error requestJob: unknow exception java.lang.NullPointerException stacktrace: java.lang.NullPointerException
   at java.util.Objects.requireNonNull(Objects.java:203)
   at java.util.Arrays$ArrayList.(Arrays.java:3813)
   at java.util.Arrays.asList(Arrays.java:3800)
   at com.sheepit.client.Configuration.getLocalCacheFiles(Configuration.java:274)
   at com.sheepit.client.Server.generateXMLForMD5cache(Server.java:815)
   at com.sheepit.client.Server.requestJob(Server.java:294)
   at com.sheepit.client.Client.run(Client.java:160)
   at com.sheepit.client.standalone.GuiSwing$ThreadClient.run(GuiSwing.java:191)
   at com.sheepit.client.Server.requestJob(Server.java:452)
   at com.sheepit.client.Client.run(Client.java:160)
   at com.sheepit.client.standalone.GuiSwing$ThreadClient.run(GuiSwing.java:191)
12-10 18:37:37 (debug) Sending error to server (type: null)

**Comment by krisives** [comment]
When does it happen?

**Comment by laurent-clouet** [comment]
To be honest, no idea :)
The trace shows a job request but I don't have context, it's one of the client who sent it.

The only thing I know:
- client version 3.182.2281 (so svn182)
- it's a windows
- it's a Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

**Comment by scribblemaniac** [comment]
Sigh, I just can't help myself sometimes. The error is caused when the cache directory is not actually a directory. You can replicate the bug by following these steps:

1. Make a folder.
2. Select the folder as the cache dir for the client.
3. Delete the folder.
4. Create a file with the same name and location as the folder had (with no extension).

Now when you start the client, [this line](https://github.com/laurent-clouet/sheepit-client/blob/master/src/com/sheepit/client/Configuration.java#L274) will throw an error because `listFiles` returns null when the file being referred to is not a directory, and `asList` throws a `NullPointerException` when passed a null parameter. The solution would be to check if listFiles returns null, and switch to the default cache directory if it is. Just be sure to check if the default directory is actually a file, or else you could end up with an infinite loop.

**Comment by laurent-clouet** [comment]
I see, i'll do some tests to create a patch for that.

Step 4 is a bit strange, i don't really kown why someone will do it...

**Comment by principat** [comment]
i think this is fixed, because at the startup it is checked that the cache dir is a directory but i'm not shure if it also works at the swing client

**Comment by MCOfficer** [comment]
is this fixed with a7e7e456ca4d5cfbeff829ac80be5a90fe408580 ?
